[project]
name = "proj"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aioserial>=1.3.1",
    "fastapi>=0.120.1",
    "smbus2>=0.5.0",
    "uvicorn[standard]>=0.38.0",
]
